import db from './src/utils/db.ts';

const lifts = [
  {
    username: 'megapotato',
    date: '2025-09-10',
    exercise: 'Barbell Squat',
    amount: 315,
    bodyweight: 156,
    additionalDetails: 'Charlie Kirk Death day',
    liftCategory: 'Compound',
  },
  {
    username: 'bunstavo',
    date: '2025-09-10',
    exercise: 'Barbell Squat',
    amount: 375,
    bodyweight: 189,
    additionalDetails: '',
    liftCategory: 'Compound',
  },
  {
    username: 'tindigm',
    date: '2025-09-10',
    exercise: 'Barbell Bench',
    amount: 495,
    bodyweight: 150,
    additionalDetails: '',
    liftCategory: 'Compound',
  },
  {
    username: 'bunstavo',
    date: '2025-09-10',
    exercise: 'Barbell Bench',
    amount: 275,
    bodyweight: 196,
    additionalDetails: '',
    liftCategory: 'Compound',
  },
  {
    username: 'megapotato',
    date: '2025-09-10',
    exercise: 'Barbell Deadlift',
    amount: 410,
    bodyweight: 160,
    additionalDetails: '',
    liftCategory: 'Compound',
  },
  {
    username: 'bunstavo',
    date: '2025-09-10',
    exercise: 'Barbell Deadlift',
    amount: 420,
    bodyweight: 205,
    additionalDetails: '',
    liftCategory: 'Compound',
  },
  {
    username: 'firefrog14',
    date: '2025-09-10',
    exercise: 'Barbell Deadlift',
    amount: 465,
    bodyweight: 170,
    additionalDetails: '',
    liftCategory: 'Compound',
  },
  {
    username: 'firefrog14',
    date: '2025-09-10',
    exercise: 'Barbell Squat',
    amount: 405,
    bodyweight: 165,
    additionalDetails: '',
    liftCategory: 'Compound',
  },
  {
    username: 'megapotato',
    date: '2025-09-10',
    exercise: 'Barbell Bench',
    amount: 245,
    bodyweight: 157,
    additionalDetails: '',
    liftCategory: 'Compound',
  },
  {
    username: 'zcxtalyst',
    date: '2025-09-12',
    exercise: 'Barbell Bench',
    amount: 190,
    bodyweight: 195,
    additionalDetails: '',
    liftCategory: 'Compound',
  },
  {
    username: 'firefrog14',
    date: '2025-09-12',
    exercise: 'Side Pressure (Wrist wrench)',
    amount: 100,
    bodyweight: 155,
    additionalDetails: '',
    liftCategory: 'ArmWrestling',
  },
  {
    username: 'megapotato',
    date: '2025-09-12',
    exercise: 'Static Pronation (Standing)',
    amount: 75,
    bodyweight: 155,
    additionalDetails: '',
    liftCategory: 'ArmWrestling',
  },
  {
    username: 'firefrog14',
    date: '2025-09-12',
    exercise: 'Static Pronation (Standing)',
    amount: 90,
    bodyweight: 160,
    additionalDetails: '',
    liftCategory: 'ArmWrestling',
  },
  {
    username: 'firefrog14',
    date: '2025-09-12',
    exercise: 'Static Pronation (Standing)',
    amount: 1,
    bodyweight: 1,
    additionalDetails: '',
    liftCategory: 'ArmWrestling',
  },
  {
    username: 'firefrog14',
    date: '2025-09-12',
    exercise: 'Barbell Bench',
    amount: 300,
    bodyweight: 165,
    additionalDetails: '',
    liftCategory: 'Compound',
  },
  {
    username: 'megapotato',
    date: '2025-09-13',
    exercise: 'Barbell Standing OHP',
    amount: 115,
    bodyweight: 160,
    additionalDetails: '',
    liftCategory: 'Compound',
  },
  {
    username: 'invi_',
    date: '2025-09-13',
    exercise: 'Barbell Standing OHP',
    amount: 135,
    bodyweight: 150,
    additionalDetails: '',
    liftCategory: 'Compound',
  },
];

const stmt = db.prepare(`
  INSERT INTO lifts (username, date, exercise, amount, bodyweight, additionalDetails, liftCategory)
  VALUES (?, ?, ?, ?, ?, ?, ?)
`);

for (const lift of lifts) {
  stmt.run(lift.username, lift.date, lift.exercise, lift.amount, lift.bodyweight, lift.additionalDetails, lift.liftCategory);
}

console.log('Imported lifts successfully!');
